### ISSUE TITLE
Getting control flow graph from binary

### ISSUE THREAD

**Issue by mxz297** [revng/revng#14]
In your CC 2017 paper, you described algorithms and techniques for building control flow graphs from binaries. I followed the steps to install revng, but cannot find an option or tool to only build control flow graph. Is there such stand-alone functionality for building control flow graph? Thanks!

**Comment by aleclearmind** [comment]
You have to lift to LLVM IR and then build the CFG of the `root` function, if you want the program-wide CFG. Otherwise, if you want the CFG of individual functions, you have to run function isolation too and build the CFG navigating the IR of the specific function you're interested in.

Please consult [GeneratedIRReference.rst](https://github.com/revng/revng/blob/develop/docs/GeneratedIRReference.rst).

**Comment by mxz297** [comment]
Thanks!
