### ISSUE TITLE
Support lifting object files

### ISSUE THREAD

**Issue by tly000** [revng/revng#28]
Hi,

are there any plans to support lifting plain `.o` object files instead of executables? I think this could be worth a try because code-to-data, data-to-code and code-to-code references are already handled by the relocations. 

Im interested in this feature because i manually corrected cross-references in a disassembled binary and reassembled it to verify that it still works. The next step for me would be to decompile this now correctly relocated binary.

**Comment by aleclearmind** [comment]
You're suggesting that things are easier since thanks to relocations you have "symbolic" references, is that right?
That makes sense. However we use QEMU to decode instructions, and I'm not sure how happy QEMU will be to see unrelocated code (jumps to zero and the like). It would need some massaging.

It's not impossible, but I don't see it as very high priority.
If you have a situation where we're having issues in detecting references, I'd be interested in looking into that.

For your specific situation, I'd just suggest to link it and throw it at rev.ng.

**Comment by tly000** [comment]
Im not quite sure if it is possible to try rev.ng because its an old windows game. the elf object was generated with "objconv" from the coff object file. Im able to compile a working version of the game for linux with "winegcc" but this results in a shared library that can be started with the wine loader.

**Comment by aleclearmind** [comment]
OK, can't you open that shared object in rev.ng?

**Comment by tly000** [comment]
thanks, ill try that!

**Comment by aleclearmind** [comment]
OK, I'm closing this since, at the current stage, handling object files is a non-goal.
