### ISSUE TITLE
Using x86 CPU flags that have an undefined value

### ISSUE THREAD

**Issue by zyt755** [revng/revng#369]
Hi, guys, several consistencies between lifting IRs and physical CPU are discovered while using.

1, In the case of the `imul` instruction, Revng modifies the `AF`, `PF`, `SF`, and `ZF` flags. Contrarily, the physical CPU does not alter these four flags in the same way, but rather maintains the status established by the preceding `add %r11, %ecx` instruction.
2, In the case of `sar`, `sal`, `shr`, and `shl` instructions, Revng overlooks the effect on the `AF` flag. Conversely, the physical CPU does take this flag into account.

The following is the assembly code.
```
0000000000400504 <Block_1>:
400504: 41 c1 fa 1f sar $0x1f,%r10d
400508: 44 01 d9 add %r11d,%ecx

000000000040050b <Block_2>:
40050b: 48 0f af d0 imul %rax,%rdx
40050f: 48 c1 ea 1f shr $0x1f,%rdx
```

The following are IRs for the instruction `0x40050b imul %rax, %rdx`.
```
  call void (ptr, i64, i32, i32, ptr, ptr, ...) @newpc(ptr nonnull @"revng.const.0x40050b:Code_x86_64", i64 4, i32 0, i32 0, ptr null, ptr null)
  %151 = load i64, ptr @rax, align 8
  %152 = load i64, ptr @rdx, align 8
  %153 = sext i64 %151 to i128
  %154 = sext i64 %152 to i128
  %155 = mul nsw i128 %153, %154
  %156 = trunc i128 %155 to i64
  %157 = lshr i128 %155, 64
  %158 = trunc i128 %157 to i64
  store i64 %156, ptr @rdx, align 8
  store i64 %156, ptr @cc_dst, align 8
  %159 = ashr i64 %156, 63
  %160 = sub i64 %159, %158
  store i64 %160, ptr @cc_src, align 8
  store i32 5, ptr @cc_op, align 4
```

**Comment by aleclearmind** [comment]
I see [here](https://www.felixcloutier.com/x86/imul)

> The SF, ZF, AF, and PF flags are undefined.

I understand your specific CPU might be preserving them, but if the docs say they are undefined, I guess we can clobber them as well.
There's a similar sentence for the [shifts documentation](https://www.felixcloutier.com/x86/sal:sar:shl:shr).
Is this creating any practical problem to you? Is there code that relies on this behavior?

Anyway, we rely on QEMU for the lifting part, so, if this poses any practical problem, we might try to fix things there.
But due to how QEMU handles x86 CPU flags, it might not be so easy. Basically QEMU does not compute the flags but saves the information to recompute them later on, if needed. Basically it saves what was the last arithmetic operation and what were its operands.

**Comment by zyt755** [comment]
Should the subsequent instruction rely on certain flags as conditions, the execution outcomes might be affected.

I concur with your perspective. I know the QEMU can bring lots of benefits. However, the manner in which QEMU manages x86 flags implies that this issue cannot be resolved merely by altering the instruction's semantics. From this standpoint, QEMU may not be the most suitable for the role of a binary lifter. Implementing precise binary analysis tools like Revng presents a significant challenge, and it seems unavoidable to encounter similar issues.

**Comment by aleclearmind** [comment]
If it's an undocumented behavior, different CPUs might behave differently, so there's no point in modeling it accurately, unless you want to target a specific CPU model. Also, compilers won't emit code relying on undocumented features.

Do you have any indication that this behavior is consistent across all x86 CPUs and/or that compilers rely on it?

If you're thinking about obfuscation... I think obfuscation is an intrinsically adversarial thing, so it will always be possible to trigger something that makes a specific static analysis tool fail.
If we accept obfuscation being an adversarial activity, then I think the right approach is avoid trying to handle the general case but enable the user to do some ad-hoc things on the IR to handle situations where people are actively trying to make our life difficult. This can be done and we can offer directions, but I don't think this is the exact reason why you opened this issue.

However, this is not a place for general discussion. We can use discuss.rev.ng or Discord for that.

If you have a *specific* problem you're trying to address, please bring it forward. Otherwise, I'd close the issue.

**Comment by zyt755** [comment]
In the following code, since the physical CPU maintains `eflags` established by the preceding `add ax, [val3]`, `jz` and `jnz` jump according to the `add ax, [val3]`. Contrarily, `jz` and `jnz` jump according to the `imul ax, [val2] ` instruction in Revng.

```
mov ax, [val1]    ; Load value of val1 into ax
add ax, [val3]    ; Add val3 to ax
imul ax, [val2]   ; Multiply ax with val2, result is in ax
mov [result], ax  ; Store the result

jz zero           ; If result is zero, jump to zero label
jnz nonzero       ; If result is not zero, jump to nonzero label
```

**Comment by aleclearmind** [comment]
It seems to me that you forged this example, which I didn't doubt it was possible `:)`.

Please answer the following specific questions:

1. Is this behavior documented anywhere?
2. Do you have any indication that this behavior is consistent across all x86 CPU models?
3. Do you have any indication that compilers rely on it? I understand one could craft assembly by hand, but the question is still important.
4. Do you have any example of real world (i.e., not crafted by you) code that exploits this behavior? If so, is this done on purpose for obfuscation purposes?

I'm trying to understand the exact scope of the problem in order to properly diagnose the problem and devise a solution.
