### ISSUE TITLE
Request: please stop worry about nonsense with the decompiler

### ISSUE THREAD

**Issue by trustednstaller** [revng/revng#414]
A minor rant because I think rev.ng has the right foundation and I want to see it succeed. The decompiler is not that important. Let's stop worrying about removing `_` characters and other shenanigans and create an entirely robust lifter (make a standalone libtcg that is also xplat) and focus tooling solely at the LLVM-IR. This will open up so many doors for scalable analysis and would be something novel other existing binary analysis frameworks do not have nor does their architecture allow for it. More than happy to help in these efforts, but "perfect" or "pure" decompilation is pointless. All we're dealing with are data transformations and particular syntactic representations. Allow users interfaces here, everything else in relation to decompilation is going backwards.

**Comment by aleclearmind** [comment]
> as someone not in an academic bubble

I'm not sure why you imply we're somehow related to academia. We've been out of that for years.
We're building an open source binary analysis framework and a product.

> having processed literally hundreds of millions of compiled binaries

A decompiler goal is to emit code that's easy to understand, if you have been processing so many binaries, your use case is likely different. However, this doesn't diminishes the importance of other use cases we are more focused on.

> not C-like pseudocode or "perfect" C code

For the bug hunting use case, the difference between a signed comparison and an unsigned comparison is critical.
In IDA, there's often so many casts that you end up hiding them.
We want to emit "perfect" C code in the sense that we emit only casts that are necessary, so you don't have to hide them. However, in order to decide which casts are implicit and which ones are not, you need to strictly adhere to *some* set of rules. Since we don't want to make up our own language that no one wants to learn, we're using C, and we adhere *strictly* to it.
Is C our dream language? No.
Is the fact that C is not our dream language a good reason to be sloppy and emit some ill-defined pseudo-C instead of C? No.
Do people want to learn our new shiny language that's better than C? No.
C, with all of its quirks, really is high level assembly, and it's also a lingua franca between all people that can read assembly.

We just use C. It's the obvious thing to do and we do it *accurately*.
Maybe one day we'll all agree that there's a new language suitable for reverse engineering, maybe we'll design it, but that's not today.

> You get to run clang-based analyzers on top of it?

CodeQL can scale pretty well and for sure it can be useful even just as a starting point to look for vulns.
Also, sometimes you want to easily copy paste a single function or a bunch of functions in your own project.
Sure, you could compile the LLVM function into an object file and link against it, but you can't modify it.

I understand this is not *your* use case, but do you *really* don't see the value in this?

What puzzles me is people saying that emitting valid C is not useful. We're all used to have expectations set so low that we don't even realize that emitting valid C is actually the very bare minimum a good design should do. And it's not even that hard for the most part.

> if I can leverage it as a standalone asset or a primitive to build off of for particular problems

We aim to be that. Emitting stuff with well defined semantics (e.g., LLVM IR vs P-code or syntactically valid C vs pseudo-C) is part of that. It's giving you a clear and well defined contract that you can rely upon.

> if you're interested in getting on a call, I can outline these for you

We are interested. Drop me an e-mail.

Overall you seem to be interested in arms race problems, such as obfuscation, which, as you're saying, cannot be generalized.
You don't seem to care about bug hunting.
You don't seem to care about understanding what a non-obfuscated program does.
These are legitimate problems that quite a lot of people have.
We're trying to build a binary analysis infrastructure, so we focus first on problem that can be generalized.

For the arms race kind of problems, which are also interesting, one can pull out the IR of some intermediate stage of the pipeline and forget the rest of the pipeline. Or, with some extra love, you can manipulate the IR in a way that can proceed in the rest of the pipeline and get you to decompiled code as well. In fact, this would be the ideal way in which we envision handling obfuscated code.

Here are our pipelines, write your LLVM pass and slap it in there:
https://github.com/revng/revng/blob/develop/share/revng/pipelines/revng-pipelines.yml
https://github.com/revng/revng-c/blob/develop/share/revng/pipelines/revng-c-pipelines.yml

Clearly, all of this is not super-well documented because it's internal, still evolving and not oriented to users but to "developers" or at very least "power users".

If you want to just write an analysis (without making any changes to the IR), here you can find an example on how to write [a simple taint analysis](https://github.com/revng/demos/tree/master/4-taint-example), without making changes to revng itself.

We'd be happy to design clean interfaces for people to implement deobfuscation techniques, and in fact we're looking into that.
But you have to understand that we have quite low incentives to dig deeply into deobfuscation techniques on our own: it takes a lot of time, if you publish it will be circumvented pretty soon and if you don't things will change anyway sooner or later, invalidating your work.
Not to mention that most people with a budget seem to consider these lost battles and just throw their best reversers for a month (or a year) at it and be happy with whatever they come out with.

Then, if we can find resources to work on some of these problems, we can better devise interfaces and "hooks" for people to easily do ad-hoc things for deobfuscation and we can all be happy.
As authors of a binary analysis framework, for the arms race problems, the best thing we can do is design easy to use hooks and interfaces.
